name: usdxworldparty
version: '0.1' 
summary: Single-line elevator pitch for your amazing snap # 79 char long summary
description: |
    Esta Es una prueba para ver como funciona
grade: devel 
confinement: devmode 

apps: 
  worldparty: 
    command: desktop-launch ./Worldparty

parts: 
    worldparty: 
        source: https://github.com/joelpg/usdxworldparty.git
        source-type: git
        plugin: autotools
  
    ffmpeg: 
        source: https://ffmpeg.org/releases/ffmpeg-3.2.2.tar.gz
        plugin: autotools
        configflags: [--enable-gpl, --disable-static, --enable-shared, --disable-programs, --disable-doc, --disable-encoders, --disable-xlib, --disable-libxcb, --disable-libxcb-shm, --disable-libx264, --disable-libx265, --disable-network, --disable-debug, --disable-indevs, --disable-outdevs, --disable-postproc, --disable-muxers, --disable-bsfs, --disable-filters, --disable-protocols, --disable-lzma, --disable-bzlib, --disable-vaapi]
        build-packages: 
            - autoconf
            - automake
            - build-essential
            - cmake
            - libass-dev
            - libfreetype6-dev
            - libmp3lame-dev
            - libopus-dev
            - libsdl1.2-dev
            - libtool
            - libva-dev
            - libvdpau-dev
            - libvorbis-dev
            - libvpx-dev
            - make
            - pkg-config
            - texinfo
            - yasm
            - zlib1g-dev
            - fpc
            - libsdl2-dev
            - libsdl2-image-dev
            - libsdl2-image-2.0-0 
            - libsdl2-2.0-0
            - libsdl2-mixer-2.0-0 
            - libsdl2-mixer-dev
            - libsdl2-net-2.0-0 
            - libsdl2-net-dev 
            - libsdl2-ttf-2.0-0 
            - libsdl2-ttf-dev 
            - libsdl2-gfx-1.0-0
            - libsdl2-gfx-dev            
            - libavdevice-dev
            - libsqlite3-0
            - libsqlite3-dev-
            - libpcre3
            - libpcre3-dev
            - ttf-dejavu
            - ttf-freefont
            - portaudio19-dev
            - lua5.1-dev
            - libpng16-16
            - libopencv-highgui-dev
            - libprojectm-dev
        organize: 
            usr/local/bin/: bin/

