name: usdxworldparty
version: "17.3RC1"
summary: UltraStar Deluxe WorldParty
description: |
  UltraStar Deluxe WorldParty is a free and open source karaoke game. 
  It allows up to six players to sing along with music using microphones in order to score points, 
  depending on the pitch of the voice and the rhythm of singing.

  UltraStar Deluxe WorldParty is a fork of the original UltraStar deluxe 1.1
  We added new features such as new selection song, avatars, themes, 
  skins, font, improved camera and mouse support, thousands of new options 
  come with this new version. Check it out!
    ----------------- 
    Official Website: http://ultrastar-es.org 
    -----------------

grade: devel 
confinement: strict 
icon: ./game/resources/icons/WorldParty.png

apps: 
  worldparty: 
    command: bin/WorldParty
    plugs: [network, pulseaudio, opengl]

parts: 
    worldparty: 
        source: https://github.com/ultrastares/usdxworldparty.git
        source-type: git
        plugin: autotools
      
        build-packages: 
            - autoconf
            - automake
            - build-essential            
            - fpc
            - make
            - pkg-config
            - texinfo
            - yasm
            - zlib1g-dev            
            - libsdl2-dev
            - libsdl2-image-dev
            - libsdl2-image-2.0-0 
            - libsdl2-2.0-0
            - libsdl2-mixer-2.0-0 
            - libsdl2-mixer-dev
            - libsdl2-net-2.0-0 
            - libsdl2-net-dev 
            - libsdl2-ttf-2.0-0 
            - libsdl2-ttf-dev 
            - libsdl2-gfx-1.0-0
            - libsdl2-gfx-dev            
            - libavdevice-dev
            - libsqlite3-0
            - libsqlite3-dev
            - libpcre3
            - libpcre3-dev
            - ttf-dejavu
            - ttf-freefont
            - portaudio19-dev
            - ffmpeg
            - liblua5.3-dev
            - libpng16-16
            - libopencv-highgui-dev
            - libprojectm-dev
                 
