
name: usdxworldparty
version: '0.1' 
summary: Single-line elevator pitch for your amazing snap # 79 char long summary
description: |
    Esta Es una prueba para ver como funciona
grade: devel 
confinement: devmode 

parts:
  worldparty:
        source: .
        plugin: autotools
